### ISSUE TITLE
Please make an initial release

### ISSUE THREAD

**Issue by johanneskoester** [pachterlab/seqspec#28]
To ease a wide adoption of this approach, we need a release as soon as possible. This way, it can for example be incorporated in Bioconda and Snakemake wrappers.

**Comment by sbooeshaghi** [comment]
Hi @johanneskoester I will be making an initial release of both the spec and the tool imminently. I am working with various groups to ensure that the current version of the specification is sufficiently defined to satisfy the needs multiple data types within the IGVF consortium, as well as flexible enough to adopt to future use-cases.

**Comment by sbooeshaghi** [comment]
Done.

https://pypi.org/project/seqspec/0.1.0/

**Comment by sbooeshaghi** [comment]
Here is the official github release

https://github.com/pachterlab/seqspec/releases/tag/v0.1.1

I bumped to v0.1.1 so pypi also reflects that as well

https://pypi.org/project/seqspec/0.1.1/
