### ISSUE TITLE
index string should take into account strand information

### ISSUE THREAD

**Issue by sidwekhande** [pachterlab/seqspec#40]
This affects chromap's `read_format`, but could affect other formats for other tools as well. The chromap index string needs to take into account strand information, and add a "-" at the end of the string when the strand is `neg`. 

For example, for this [seqspec](https://github.com/detrout/y2ave_seqspecs/blob/main/Team_1_CharacterizationMcGinnis_Dataset1_10X_Lane_1_seqspec.yaml), the correct index string to align the fastqs using chromap is `bc:8:23:-,r1:0:49,r2:0:49`. Current implementation will return `bc:8:23,r1:0:49,r2:0:49` (missing the extra ":-" at end of bc string).

**Comment by sbooeshaghi** [comment]
Can you write the seqspec command you are using to generate the chromap sting?

**Comment by sidwekhande** [comment]
Yes, the command is:
`seqspec index -m atac -r ATAC_1_S358_L007_R1_001.fastq.gz,ATAC_1_S358_L007_R3_001.fastq.gz,ATAC_1_S358_L007_R2_001.fastq.gz -t chromap Team_1_CharacterizationMcGinnis_Dataset1_10X_Lane_1_seqspec.yaml`

**Comment by sbooeshaghi** [comment]
This has been fixed in https://github.com/pachterlab/seqspec/commit/e1ae2eb7e3fe18a3e1b73c4f97dc803d68e76a69. Please install devel, test, and reopen if not fixed.
