### ISSUE TITLE
source file for pypi

### ISSUE THREAD

**Issue by visze** [pachterlab/seqspec#45]
Hi,

I want to put seqspec into bioconda. The easiest way is to go through pypi and it wil automatically update conda if there is a new pypi version.

But therefore you have also to upload the source files to pypi. So after building your distribution you also need to build the source distribution. This can be done with `python setup.py sdist` and afterwards uploading to pypi.

thanks!

**Comment by sbooeshaghi** [comment]
Thank you for doing this. I am planning on merging devel with main and pushing a minor version bump soon and in doing so will upload the source files to pypi.

**Comment by visze** [comment]
Hi Sina. Any updates here? would be great to push it to conda!

**Comment by sbooeshaghi** [comment]
Yes. I released the `devel` branch internally to the group I am working with and am waiting to hear feedback from them. If everything looks good then I will merge and release soon (including uploading the source files to pypi). My hope is that this will happen no later than end of September.

**Comment by sbooeshaghi** [comment]
Done. https://pypi.org/project/seqspec/0.3.0/

**Comment by visze** [comment]
It is on (bio)conda: https://bioconda.github.io/recipes/seqspec/README.html#package-package%20&#x27;seqspec&#x27;

**Comment by visze** [comment]
Already did! But takes a while unti it is there

**Comment by visze** [comment]
54 people already downloaded seqspec :-)
