### ISSUE TITLE
Feature request: grouping of sequencing runs

### ISSUE THREAD

**Issue by visze** [pachterlab/seqspec#46]
`sequence_spec` can only be single read files. But maybe a hierarchy might be good when resequencing data and want to add to the actual seqspec file. Right now, the only possibility I see is concatenating fastq files which is a waste of disk pace and an additional processing step that can be avoided.

**Comment by sbooeshaghi** [comment]
Hi- thank you for your comments. Can you clarify with an example? That would help me better understand your request.

**Comment by sbooeshaghi** [comment]
I have solved the issue of specifying multiple under a single read object which will allow a grouping of sequencing runs. The solution groups multiple read files into "Read" object as a list of "File` objects. This is currently an undocumented feature that is present in the `devel` branch. Check out the template here. Note the "Read" object now has a property "files" that allows users to list out multiple FASTQ files corresponding to that read.

https://github.com/pachterlab/seqspec/blob/devel/examples/specs/template/10xv3-template.yaml

An additional note: fastq files *must* be paired appropriately between reads. E.G. Read 1 from lane 2 must be in the same order in the "files" object as the corresponding Read 2 from lane 2. I will update the documentation soon to reflect this enhancement.

**Comment by sbooeshaghi** [comment]
Hi- this is now supported in the `devel` branch of the code. Please see the documentation: https://pachterlab.github.io/seqspec/seqspec-file#mapping-files-to-reads
